/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.desktop;

import com.mycompany.desktop.API.APIClient;
import com.mycompany.desktop.API.AuthService;
import com.mycompany.desktop.models.Admin;
import com.mycompany.desktop.models.*;
import com.mycompany.desktop.utils.SessionManager;
import com.mycompany.desktop.utils.ValidationUtils;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

import com.google.gson.Gson;

/**
 *
 * @author admin
 */
public class AdminHome extends javax.swing.JFrame {

    private AuthService authService;
    private List<Department> listDepartments;
    private List<Doctor> listDoctors;

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        authService = APIClient.getAuthService();
        this.setExtendedState(Login.MAXIMIZED_BOTH);
        loadAdminProfile();
        loadListDepartments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_admin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_admin_name = new javax.swing.JLabel();
        jLabel_admin_email = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel_khoa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_departments = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField_department_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_department_description = new javax.swing.JTextArea();
        jLabel155 = new javax.swing.JLabel();
        jTextField_department_anhNen = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_doctor = new javax.swing.JTable();
        jLabel_dsbs_khoa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_thongTinBacSi = new javax.swing.JLabel();
        jTextField_bacsi_name = new javax.swing.JTextField();
        jTextField_bacsi_phone = new javax.swing.JTextField();
        jButton_themBacSi = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_bacsi_brithdate = new javax.swing.JTextField();
        jPasswordField_bacsi_pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel_bacsi_loi = new javax.swing.JLabel();
        jTextField_bacsi_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_bacsi_nam = new javax.swing.JRadioButton();
        jRadioButton_bacsi_nu = new javax.swing.JRadioButton();
        jTextField_bacsi_address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_bacsi_avatar_url = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_bacsi_department_id = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_bacsi_description = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Trang ADMIN");

        jLabel_admin_name.setText("Tên:");

        jLabel_admin_email.setText("Gmail:");

        jButton6.setText("Đổi mật khẩu");

        jButton7.setText("Đăng xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_adminLayout = new javax.swing.GroupLayout(jPanel_admin);
        jPanel_admin.setLayout(jPanel_adminLayout);
        jPanel_adminLayout.setHorizontalGroup(
            jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_adminLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jLabel1)
                    .addComponent(jLabel_admin_name)
                    .addComponent(jLabel_admin_email))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel_adminLayout.setVerticalGroup(
            jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_admin_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_admin_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(17, 17, 17))
        );

        jTable_departments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable_departments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Tên Khoa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_departments.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_departments.setName(""); // NOI18N
        jTable_departments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_departments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_departments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_departmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_departments);
        if (jTable_departments.getColumnModel().getColumnCount() > 0) {
            jTable_departments.getColumnModel().getColumn(0).setMinWidth(20);
            jTable_departments.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_departments.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Quản Lý Khoa Khám");

        jLabel6.setText("Tên Khoa:");

        jLabel7.setText("Mô tả:");

        jButton5.setText("Làm mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea_department_description.setColumns(20);
        jTextArea_department_description.setRows(5);
        jScrollPane5.setViewportView(jTextArea_department_description);

        jLabel155.setText("Ảnh nền:");

        javax.swing.GroupLayout jPanel_khoaLayout = new javax.swing.GroupLayout(jPanel_khoa);
        jPanel_khoa.setLayout(jPanel_khoaLayout);
        jPanel_khoaLayout.setHorizontalGroup(
            jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_khoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_khoaLayout.createSequentialGroup()
                        .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel_khoaLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_khoaLayout.createSequentialGroup()
                        .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_khoaLayout.createSequentialGroup()
                                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_department_name)
                                    .addComponent(jScrollPane5)))
                            .addGroup(jPanel_khoaLayout.createSequentialGroup()
                                .addComponent(jLabel155)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_department_anhNen))
                            .addGroup(jPanel_khoaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel_khoaLayout.setVerticalGroup(
            jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_khoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_department_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel155)
                    .addComponent(jTextField_department_anhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_khoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable_doctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "Email", "Số điện thoại", "Ngày sinh"
            }
        ));
        jTable_doctor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_doctorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_doctor);

        jLabel_dsbs_khoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_dsbs_khoa.setText("Danh sách bác sĩ khoa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel_dsbs_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_dsbs_khoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel_thongTinBacSi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_thongTinBacSi.setText("Thông tin bác sĩ:");

        jTextField_bacsi_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bacsi_phoneActionPerformed(evt);
            }
        });

        jButton_themBacSi.setText("Thêm");
        jButton_themBacSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themBacSiActionPerformed(evt);
            }
        });

        jButton8.setText("Sửa");

        jButton9.setText("Xóa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Phone");

        jLabel8.setText("BirthDate     YYYY-MM-DD");

        jPasswordField_bacsi_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_bacsi_passActionPerformed(evt);
            }
        });

        jLabel10.setText("Password");

        jTextField_bacsi_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bacsi_emailActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        buttonGroup1.add(jRadioButton_bacsi_nam);
        jRadioButton_bacsi_nam.setText("Male");

        buttonGroup1.add(jRadioButton_bacsi_nu);
        jRadioButton_bacsi_nu.setText("Female");

        jLabel9.setText("Gender");

        jLabel11.setText("Address");

        jLabel12.setText("Description");

        jLabel13.setText("Avatar_url");

        jLabel14.setText("Department_id");

        jTextArea_bacsi_description.setColumns(20);
        jTextArea_bacsi_description.setRows(5);
        jScrollPane4.setViewportView(jTextArea_bacsi_description);

        jButton10.setText("Làm mới");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_bacsi_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_bacsi_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_thongTinBacSi)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jButton_themBacSi)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton8)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton9)))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))
                            .addComponent(jTextField_bacsi_department_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_bacsi_avatar_url, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(jTextField_bacsi_address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_bacsi_loi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_bacsi_phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_bacsi_brithdate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_bacsi_pass, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_bacsi_nam)
                                .addGap(32, 32, 32)
                                .addComponent(jRadioButton_bacsi_nu))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(0, 230, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_thongTinBacSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jTextField_bacsi_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_brithdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_bacsi_nam)
                    .addComponent(jRadioButton_bacsi_nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_bacsi_avatar_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(jTextField_bacsi_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(jPasswordField_bacsi_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_bacsi_loi)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_themBacSi)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Bác Sĩ", jPanel3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý lịch khám", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 506, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAdminProfile() {
        String token = SessionManager.getInstance().getToken();

        authService.getAdminProfile(token).enqueue(new Callback<Admin>() {
            @Override
            public void onResponse(Call<Admin> call, Response<Admin> response) {
                if (response.isSuccessful() && response.body() != null) {
                    jLabel_admin_name.setText(response.body().getFull_name());
                    jLabel_admin_email.setText(response.body().getEmail());
                } else {
                    // Handle error
                    if (response.code() == 401) {
                        // Token expired or invalid
                        JOptionPane.showMessageDialog(null, "Session expired. Please login again.");
                        SessionManager.getInstance().clearSession();
                        new Login().setVisible(true);
                        AdminHome.this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to load profile. Please try again1.");

                    }
                    JOptionPane.showMessageDialog(null, "Failed to load profile. Please try again2.");
                }
            }

            @Override
            public void onFailure(Call<Admin> call, Throwable thrwbl) {
                JOptionPane.showMessageDialog(null, "Network error");
            }
        });
    }

    private void loadListDepartments() {
        String token = SessionManager.getInstance().getToken();
        listDepartments = new ArrayList<>();

        authService.getDepartments(token).enqueue(new Callback<List<Department>>() {
            @Override
            public void onResponse(Call<List<Department>> call, Response<List<Department>> response) {
                if (response.isSuccessful() && response.body() != null) {
                    listDepartments = response.body();
                    loadTableDepartment(listDepartments);
                } else {
                    System.out.println("API Error: " + response.code() + " - " + response.message());
                    JOptionPane.showMessageDialog(null, "Failed to load departments!\nError: " + response.message());
                }
            }

            @Override
            public void onFailure(Call<List<Department>> call, Throwable thrwbl) {
                JOptionPane.showMessageDialog(null, "Network error: " + thrwbl.getMessage());
            }
        });
    }

    private void loadListDoctors(int department_id) {
        String token = SessionManager.getInstance().getToken();
        listDoctors = new ArrayList<>();

        authService.getListDoctors(token, department_id).enqueue(new Callback<List<Doctor>>() {
            @Override
            public void onResponse(Call<List<Doctor>> call, Response<List<Doctor>> response) {

                if (response.isSuccessful() && response.body() != null) {
                    listDoctors = response.body();
                    loadTableDoctor(listDoctors);
                } else {
                    System.out.println("API Error: " + response.code() + " - " + response.message());
                    JOptionPane.showMessageDialog(null, "Failed to load departments!\nError: " + response.message());
                }
            }

            @Override
            public void onFailure(Call<List<Doctor>> call, Throwable thrwbl) {
                JOptionPane.showMessageDialog(null, "Network error: " + thrwbl.getMessage());
            }
        });

    }

    private void loadTableDoctor(List<Doctor> doctors) {
        DefaultTableModel model = (DefaultTableModel) jTable_doctor.getModel();
        model.setRowCount(0);

        for (Doctor doctor : doctors) {
            model.addRow(new Object[]{doctor.getFull_name(), doctor.getEmail(), doctor.getPhone(), doctor.getDate_of_birth()});
        }
    }

    private void loadTableDepartment(List<Department> departments) {
        DefaultTableModel model = (DefaultTableModel) jTable_departments.getModel();
        model.setRowCount(0);

        for (Department dept : departments) {
            model.addRow(new Object[]{dept.getId(), dept.getName(), dept.getDescription()});
        }

    }

    private void registerDoctor() {
        Doctor doctorRequest = getDoctorFromUI();

        char[] passChars = jPasswordField_bacsi_pass.getPassword();
        String password = new String(passChars);

        // Kiểm tra dữ liệu nhập vào
        if (!ValidationUtils.isValidName(doctorRequest.getFull_name())) {
            jLabel_bacsi_loi.setText("Please enter your name");
            jTextField_bacsi_name.requestFocus();
            return;
        }

        if (!ValidationUtils.isValidEmail(doctorRequest.getEmail())) {
            jLabel_bacsi_loi.setText("Please enter a valid email");
            jTextField_bacsi_email.requestFocus();
            return;
        }

        if (!ValidationUtils.isValidPassword(password)) {
            jLabel_bacsi_loi.setText("Password must be at least 8 characters");
            jPasswordField_bacsi_pass.requestFocus();
            return;
        }

        if (!doctorRequest.getPhone().isEmpty() && !ValidationUtils.isValidPhone(doctorRequest.getPhone())) {
            jLabel_bacsi_loi.setText("Please enter a valid phone number");
            jTextField_bacsi_phone.requestFocus();
            return;
        }

        // Lấy khoa đã chọn
        int row = jTable_departments.getSelectedRow();
        if (row == -1) {
            jLabel_bacsi_loi.setText("Please select a department");
            return;
        }
        int id_department = (int) jTable_departments.getValueAt(row, 0);

        // Chuyển đổi birthDate sang Date
        // Tạo request object
        System.out.println("Doctor Data: " + new Gson().toJson(doctorRequest));
        String token = SessionManager.getInstance().getToken();

        authService.registerDoctor(token, doctorRequest).enqueue(new Callback<Doctor>() {
            @Override
            public void onResponse(Call<Doctor> call, Response<Doctor> response) {
                if (response.isSuccessful() && response.body() != null) {
                    JOptionPane.showMessageDialog(null, "Registration successful! Please login. " + response.message());
                    clearDoctorUI();
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to load doctor!\nError: " + response.message());
                }

            }

            @Override
            public void onFailure(Call<Doctor> call, Throwable thrwbl) {
                JOptionPane.showMessageDialog(null, "Network error: " + thrwbl.getMessage());

            }
        });

    }

    private Doctor getDoctorFromUI() {
        Doctor doctor = new Doctor();

        doctor.setFull_name(jTextField_bacsi_name.getText().trim());
        doctor.setEmail(jTextField_bacsi_email.getText().trim());
        doctor.setPhone(jTextField_bacsi_phone.getText().trim());
        doctor.setDate_of_birth(jTextField_bacsi_brithdate.getText().trim());

        if (jRadioButton_bacsi_nam.isSelected()) {
            doctor.setGender("Male");
        } else if (jRadioButton_bacsi_nu.isSelected()) {
            doctor.setGender("Female");
        }

        char[] passChars = jPasswordField_bacsi_pass.getPassword();
        String password = new String(passChars);
        doctor.setPassword(password);
        doctor.setAddress(jTextField_bacsi_address.getText().trim()); // Nếu có trường địa chỉ
        doctor.setDescription(jTextArea_bacsi_description.getText().trim());
        doctor.setAvatar_url(jTextField_bacsi_avatar_url.getText().trim());

        try {
            doctor.setDepartment_id(Integer.parseInt(jTextField_bacsi_department_id.getText().trim()));
        } catch (NumberFormatException e) {
            doctor.setDepartment_id(0); // Giá trị mặc định nếu không hợp lệ
        }

        return doctor;
    }

    private Department getDepartmentFromUI() {
        Department department = new Department();
        department.setName(jTextField_department_name.getText().trim());
        department.setDescription(jTextArea_department_description.getText().trim());
        department.setAvatar_url(jTextField_department_anhNen.getText().trim());
        return department;
    }

    private void setDoctor_toUI(Doctor doctorResponse) {
        jLabel_thongTinBacSi.setText("Thông tin bác sĩ: " + doctorResponse.getFull_name());

        jTextField_bacsi_name.setText(doctorResponse.getFull_name());
        jTextField_bacsi_email.setText(doctorResponse.getEmail());
        jTextField_bacsi_phone.setText(doctorResponse.getPhone());
        jTextField_bacsi_brithdate.setText(doctorResponse.getDate_of_birth());
        String gender = doctorResponse.getGender();
        if (gender.equals("Male")) {
            jRadioButton_bacsi_nam.setSelected(true);
        } else if (gender.equals("Female")) {
            jRadioButton_bacsi_nu.setSelected(true);
        }

        jTextArea_bacsi_description.setText(doctorResponse.getDescription());
        jTextArea_bacsi_description.setLineWrap(true);
        jTextArea_bacsi_description.setWrapStyleWord(true);
        jTextField_bacsi_address.setText(doctorResponse.getAddress());

        jTextField_bacsi_avatar_url.setText(doctorResponse.getAvatar_url());
        jTextField_bacsi_department_id.setText(doctorResponse.getDepartment_id() + "");
        jPasswordField_bacsi_pass.setText("");
    }

    private void setDeparment_toUI(Department department) {
        jTextField_department_name.setText(department.getName());
        jTextArea_department_description.setText(department.getDescription());
        jTextArea_department_description.setLineWrap(true); // Tự động xuống dòng
        jTextArea_department_description.setWrapStyleWord(true); // Xuống dòng theo từ
        jTextField_department_anhNen.setText(department.getAvatar_url());
        loadListDoctors(department.getId());;
        jLabel_dsbs_khoa.setText("Danh sách bác sĩ khoa: " + department.getName());
    }

    private void clearDoctorUI() {
        jLabel_thongTinBacSi.setText("Thông tin bác sĩ ");
        jTextField_bacsi_name.setText("");
        jTextField_bacsi_email.setText("");
        jTextField_bacsi_phone.setText("");
        jTextField_bacsi_brithdate.setText("");
        jPasswordField_bacsi_pass.setText("");
        jTextArea_bacsi_description.setText("");
        jTextField_bacsi_address.setText("");
        jTextField_bacsi_avatar_url.setText("");
        //jTextField_bacsi_department_id.setText("");
    }

    private void clearDepartmentUI() {
        jTextField_department_name.setText("");
        jTextArea_department_description.setText("");
        jTextField_department_anhNen.setText("");
        jLabel_dsbs_khoa.setText("Danh sách bác sĩ khoa: ");
    }


    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField_bacsi_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bacsi_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bacsi_phoneActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField_department_name.setText("");
        jTextArea_department_description.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable_departmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_departmentsMouseClicked
        int row = jTable_departments.getSelectedRow();

        if (row != -1) { // Kiểm tra nếu có dòng nào đó được chọn
            Department department = listDepartments.get(row);
            setDeparment_toUI(department);
        }
        jTextField_bacsi_department_id.setText(jTable_departments.getValueAt(row, 0) + "");
    }//GEN-LAST:event_jTable_departmentsMouseClicked

    private void jTextField_bacsi_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bacsi_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bacsi_emailActionPerformed

    private void jButton_themBacSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themBacSiActionPerformed
        registerDoctor();
    }//GEN-LAST:event_jButton_themBacSiActionPerformed

    private void jPasswordField_bacsi_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_bacsi_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_bacsi_passActionPerformed

    private void jTable_doctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_doctorMouseClicked
        int row = jTable_doctor.getSelectedRow();

        if (row != -1) { // Kiểm tra nếu có dòng nào đó được chọn
            Doctor doctorResponse = listDoctors.get(row);
            setDoctor_toUI(doctorResponse);
        }
    }//GEN-LAST:event_jTable_doctorMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        clearDoctorUI();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SessionManager.getInstance().clearSession();

        new Login().setVisible(true);
        AdminHome.this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_themBacSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_admin_email;
    private javax.swing.JLabel jLabel_admin_name;
    private javax.swing.JLabel jLabel_bacsi_loi;
    private javax.swing.JLabel jLabel_dsbs_khoa;
    private javax.swing.JLabel jLabel_thongTinBacSi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_admin;
    private javax.swing.JPanel jPanel_khoa;
    private javax.swing.JPasswordField jPasswordField_bacsi_pass;
    private javax.swing.JRadioButton jRadioButton_bacsi_nam;
    private javax.swing.JRadioButton jRadioButton_bacsi_nu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable_departments;
    private javax.swing.JTable jTable_doctor;
    private javax.swing.JTextArea jTextArea_bacsi_description;
    private javax.swing.JTextArea jTextArea_department_description;
    private javax.swing.JTextField jTextField_bacsi_address;
    private javax.swing.JTextField jTextField_bacsi_avatar_url;
    private javax.swing.JTextField jTextField_bacsi_brithdate;
    private javax.swing.JTextField jTextField_bacsi_department_id;
    private javax.swing.JTextField jTextField_bacsi_email;
    private javax.swing.JTextField jTextField_bacsi_name;
    private javax.swing.JTextField jTextField_bacsi_phone;
    private javax.swing.JTextField jTextField_department_anhNen;
    private javax.swing.JTextField jTextField_department_name;
    // End of variables declaration//GEN-END:variables
}
